 name: ash003project
 on:
  push:
     branches: [ main ]

  workflow_dispatch:
 jobs:
  
  build:
    
    runs-on: ubuntu-latest
   
    steps:
    
    - uses: actions/checkout@v2

   
    - name: Install NodeJs
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - uses: borales/actions-yarn@v2.3.0
      with:
       cmd: install 
    - name: Build react App
      run: yarn build   
    - name: Install Surge
      run: npm install --global surge
    - name: Run Surge
      run: surge ./build ash003project.surge.sh --token ${{secrets.project3}}

